__author__ = 'Ravi'

import struct
class Begin:
    def __init__(self):
        try:
            self.fp=open("forums.bin","rb+")
            self.fp.seek(4*0)
            x=self.fp.read(4)
            self.users_offset=struct.unpack("I",x)
            self.fp.seek(4*1)
            self.no_of_users=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*2)
            self.forum_offset=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*3)
            self.ques_offset=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*4)
            self.act_ques_pointer=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*5)
            self.no_of_ques=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*6)
            self.ans_offset=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*7)
            self.act_ans_pointer=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*8)
            self.no_of_ans=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*9)
            self.rep_offset=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*10)
            self.act_reply_pointer=struct.unpack("I",self.fp.read(4))
            self.fp.seek(4*11)
            self.no_of_rep=struct.unpack("I",self.fp.read(4))
            self.fp.close()
        except IOError:
            self.fp=open("forums.bin","wb+")
            self.users_offset=1024
            self.no_of_users=0
            self.forum_offset=1024*1024
            self.ques_offset=2*1024*1024
            self.act_ques_pointer=7*1024*1024
            self.no_of_ques=1
            self.ans_offset=4*1024*1024
            self.act_ans_pointer=207*1024*1024
            self.no_of_ans=1
            self.rep_offset=6*1024*1024
            self.act_reply_pointer=807*1024*1024
            self.no_of_rep=1
            self.fp.seek(0)
            x=struct.pack("I",1024)
            self.fp.write(x)
            self.fp.seek(4)
            self.fp.write(struct.pack("I",self.no_of_users))
            self.fp.seek(4*2)
            self.fp.write(struct.pack("I",self.forum_offset))
            self.fp.seek(4*3)
            self.fp.write(struct.pack("I",self.ques_offset))
            self.fp.seek(4*4)
            self.fp.write(struct.pack("I",self.act_ques_pointer))
            self.fp.seek(4*5)
            self.fp.write(struct.pack("I",self.no_of_ques))
            self.fp.seek(4*6)
            self.fp.write(struct.pack("I",self.ans_offset))
            self.fp.seek(4*7)
            self.fp.write(struct.pack("I",self.act_ans_pointer))
            self.fp.seek(4*8)
            self.fp.write(struct.pack("I",self.no_of_ans))
            self.fp.seek(4*9)
            self.fp.write(struct.pack("I",self.rep_offset))
            self.fp.seek(4*10)
            self.fp.write(struct.pack("I",self.act_reply_pointer))
            self.fp.seek(4*11)
            self.fp.write(struct.pack("I",self.no_of_rep))
            self.fp.close()
